// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_metrics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveOrganizations = `-- name: CountActiveOrganizations :one
SELECT COUNT(*)::bigint FROM organizations WHERE deleted_at IS NULL
`

func (q *Queries) CountActiveOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrganizations)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*)::bigint FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getDailyRevenue = `-- name: GetDailyRevenue :many
SELECT
    DATE(o.created_at AT TIME ZONE 'America/Sao_Paulo')::text AS day,
    COALESCE(SUM(o.total_cents), 0)::bigint                   AS revenue_cents,
    COUNT(*)::bigint                                        AS orders_count
FROM orders o
WHERE o.status = 'PAID'
  AND o.created_at >= NOW() - INTERVAL '30 days'
  AND ($1::uuid IS NULL OR EXISTS (
    SELECT 1 FROM tickets t
    JOIN events e ON e.id = t.event_id
    JOIN venues v ON v.id = e.venue_id
    WHERE t.order_id = o.id AND v.organization_id = $1
))
GROUP BY 1
ORDER BY 1
`

type GetDailyRevenueRow struct {
	Day          string `json:"day"`
	RevenueCents int64  `json:"revenue_cents"`
	OrdersCount  int64  `json:"orders_count"`
}

func (q *Queries) GetDailyRevenue(ctx context.Context, filterOrganizationID pgtype.UUID) ([]GetDailyRevenueRow, error) {
	rows, err := q.db.Query(ctx, getDailyRevenue, filterOrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyRevenueRow{}
	for rows.Next() {
		var i GetDailyRevenueRow
		if err := rows.Scan(&i.Day, &i.RevenueCents, &i.OrdersCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinancialTotals = `-- name: GetFinancialTotals :one
SELECT
    COALESCE(SUM(o.total_cents) FILTER (WHERE o.status = 'PAID'), 0)::bigint                                                AS revenue_all_cents,
    COUNT(*) FILTER (WHERE o.status = 'PAID')::bigint                                                                       AS paid_orders_all,
    COALESCE(SUM(o.total_cents) FILTER (WHERE o.status = 'PAID' AND o.created_at >= NOW() - INTERVAL '30 days'), 0)::bigint AS revenue_30d_cents,
    COUNT(*) FILTER (WHERE o.status = 'PAID' AND o.created_at >= NOW() - INTERVAL '30 days')::bigint                        AS paid_orders_30d
FROM orders o
WHERE ($1::uuid IS NULL OR EXISTS (
    SELECT 1 FROM tickets t
    JOIN events e ON e.id = t.event_id
    JOIN venues v ON v.id = e.venue_id
    WHERE t.order_id = o.id AND v.organization_id = $1
))
`

type GetFinancialTotalsRow struct {
	RevenueAllCents int64 `json:"revenue_all_cents"`
	PaidOrdersAll   int64 `json:"paid_orders_all"`
	Revenue30dCents int64 `json:"revenue_30d_cents"`
	PaidOrders30d   int64 `json:"paid_orders_30d"`
}

func (q *Queries) GetFinancialTotals(ctx context.Context, filterOrganizationID pgtype.UUID) (GetFinancialTotalsRow, error) {
	row := q.db.QueryRow(ctx, getFinancialTotals, filterOrganizationID)
	var i GetFinancialTotalsRow
	err := row.Scan(
		&i.RevenueAllCents,
		&i.PaidOrdersAll,
		&i.Revenue30dCents,
		&i.PaidOrders30d,
	)
	return i, err
}

const getOrderStatusCounts = `-- name: GetOrderStatusCounts :many
SELECT
    o.status,
    COUNT(*)::bigint                                                                                  AS count_all,
    COUNT(*) FILTER (WHERE o.created_at >= NOW() - INTERVAL '30 days')::bigint                          AS count_30d,
    COALESCE(SUM(o.total_cents), 0)::bigint                                                             AS amount_all_cents,
    COALESCE(SUM(o.total_cents) FILTER (WHERE o.created_at >= NOW() - INTERVAL '30 days'), 0)::bigint     AS amount_30d_cents
FROM orders o
WHERE ($1::uuid IS NULL OR EXISTS (
    SELECT 1 FROM tickets t
    JOIN events e ON e.id = t.event_id
    JOIN venues v ON v.id = e.venue_id
    WHERE t.order_id = o.id AND v.organization_id = $1
))
GROUP BY o.status
`

type GetOrderStatusCountsRow struct {
	Status         string `json:"status"`
	CountAll       int64  `json:"count_all"`
	Count30d       int64  `json:"count_30d"`
	AmountAllCents int64  `json:"amount_all_cents"`
	Amount30dCents int64  `json:"amount_30d_cents"`
}

func (q *Queries) GetOrderStatusCounts(ctx context.Context, filterOrganizationID pgtype.UUID) ([]GetOrderStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, getOrderStatusCounts, filterOrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderStatusCountsRow{}
	for rows.Next() {
		var i GetOrderStatusCountsRow
		if err := rows.Scan(
			&i.Status,
			&i.CountAll,
			&i.Count30d,
			&i.AmountAllCents,
			&i.Amount30dCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgRevenueSummary = `-- name: GetOrgRevenueSummary :many
WITH order_org AS (
    SELECT o.id AS order_id,
           o.total_cents,
           o.status,
           o.created_at,
           v.organization_id
    FROM orders o
    JOIN tickets t ON t.order_id = o.id
    JOIN events e ON e.id = t.event_id
    JOIN venues v ON v.id = e.venue_id
    GROUP BY o.id, o.total_cents, o.status, o.created_at, v.organization_id
)
SELECT
    org.id AS organization_id,
    org.name AS organization_name,
    org.slug AS organization_slug,
    COALESCE(SUM(oo.total_cents) FILTER (WHERE oo.status = 'PAID' AND oo.created_at >= NOW() - INTERVAL '30 days'), 0)::bigint AS revenue_30d_cents,
    COALESCE(SUM(oo.total_cents) FILTER (WHERE oo.status = 'PAID'), 0)::bigint AS revenue_all_cents
FROM organizations org
LEFT JOIN order_org oo ON oo.organization_id = org.id
WHERE org.deleted_at IS NULL
GROUP BY org.id, org.name, org.slug
ORDER BY revenue_30d_cents DESC, org.name ASC
`

type GetOrgRevenueSummaryRow struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	OrganizationName string    `json:"organization_name"`
	OrganizationSlug string    `json:"organization_slug"`
	Revenue30dCents  int64     `json:"revenue_30d_cents"`
	RevenueAllCents  int64     `json:"revenue_all_cents"`
}

func (q *Queries) GetOrgRevenueSummary(ctx context.Context) ([]GetOrgRevenueSummaryRow, error) {
	rows, err := q.db.Query(ctx, getOrgRevenueSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrgRevenueSummaryRow{}
	for rows.Next() {
		var i GetOrgRevenueSummaryRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.Revenue30dCents,
			&i.RevenueAllCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResaleMetrics = `-- name: GetResaleMetrics :one
WITH listing_orders AS (
    SELECT
        l.status AS listing_status,
        o.id AS order_id,
        o.kind AS order_kind,
        o.status AS order_status,
        o.total_cents,
        o.created_at AS order_created_at
    FROM ticket_resale_listings l
    JOIN tickets t ON t.id = l.ticket_id
    JOIN events e ON e.id = t.event_id
    JOIN venues v ON v.id = e.venue_id
    LEFT JOIN orders o ON o.resale_listing_id = l.id
    WHERE ($1::uuid IS NULL OR v.organization_id = $1)
)
SELECT
    COALESCE(COUNT(*) FILTER (WHERE listing_status = 'active'), 0)::bigint AS active_listings,
    COALESCE(COUNT(*) FILTER (WHERE listing_status = 'cancelled'), 0)::bigint AS cancelled_listings,
    COALESCE(COUNT(*) FILTER (WHERE listing_status = 'sold'), 0)::bigint AS sold_listings_all,
    COALESCE(COUNT(*) FILTER (WHERE order_id IS NOT NULL AND order_kind = 'resale' AND order_status = 'PAID'), 0)::bigint AS resale_paid_orders_all,
    COALESCE(SUM(total_cents) FILTER (WHERE order_kind = 'resale' AND order_status = 'PAID'), 0)::bigint AS resale_revenue_all_cents,
    COALESCE(COUNT(*) FILTER (WHERE order_kind = 'resale' AND order_status = 'PAID' AND order_created_at >= NOW() - INTERVAL '30 days'), 0)::bigint AS resale_paid_orders_30d,
    COALESCE(SUM(total_cents) FILTER (WHERE order_kind = 'resale' AND order_status = 'PAID' AND order_created_at >= NOW() - INTERVAL '30 days'), 0)::bigint AS resale_revenue_30d_cents
FROM listing_orders
`

type GetResaleMetricsRow struct {
	ActiveListings        int64 `json:"active_listings"`
	CancelledListings     int64 `json:"cancelled_listings"`
	SoldListingsAll       int64 `json:"sold_listings_all"`
	ResalePaidOrdersAll   int64 `json:"resale_paid_orders_all"`
	ResaleRevenueAllCents int64 `json:"resale_revenue_all_cents"`
	ResalePaidOrders30d   int64 `json:"resale_paid_orders_30d"`
	ResaleRevenue30dCents int64 `json:"resale_revenue_30d_cents"`
}

func (q *Queries) GetResaleMetrics(ctx context.Context, filterOrganizationID pgtype.UUID) (GetResaleMetricsRow, error) {
	row := q.db.QueryRow(ctx, getResaleMetrics, filterOrganizationID)
	var i GetResaleMetricsRow
	err := row.Scan(
		&i.ActiveListings,
		&i.CancelledListings,
		&i.SoldListingsAll,
		&i.ResalePaidOrdersAll,
		&i.ResaleRevenueAllCents,
		&i.ResalePaidOrders30d,
		&i.ResaleRevenue30dCents,
	)
	return i, err
}

const getStadiumSummary = `-- name: GetStadiumSummary :many
SELECT
    v.id,
    v.name,
    v.city,
    v.state,
    v.capacity,
    COUNT(DISTINCT e.id) FILTER (WHERE e.id IS NOT NULL)::bigint                                            AS event_count,
    COUNT(DISTINCT s.id) FILTER (WHERE s.id IS NOT NULL)::bigint                                            AS total_seats,
    COUNT(DISTINCT t.id) FILTER (WHERE o.status = 'PAID')::bigint                                           AS tickets_sold,
    COALESCE(SUM(s.price_cents) FILTER (WHERE o.status = 'PAID' AND t.id IS NOT NULL), 0)::bigint           AS revenue_cents
FROM venues v
LEFT JOIN events e ON e.venue_id = v.id AND e.deleted_at IS NULL
LEFT JOIN seats s ON s.event_id = e.id
LEFT JOIN tickets t ON t.seat_id = s.id
LEFT JOIN orders o ON o.id = t.order_id
WHERE v.deleted_at IS NULL
  AND ($1::uuid IS NULL OR v.organization_id = $1)
GROUP BY v.id, v.name, v.city, v.state, v.capacity
ORDER BY revenue_cents DESC, v.name
`

type GetStadiumSummaryRow struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	City         string    `json:"city"`
	State        string    `json:"state"`
	Capacity     int32     `json:"capacity"`
	EventCount   int64     `json:"event_count"`
	TotalSeats   int64     `json:"total_seats"`
	TicketsSold  int64     `json:"tickets_sold"`
	RevenueCents int64     `json:"revenue_cents"`
}

func (q *Queries) GetStadiumSummary(ctx context.Context, filterOrganizationID pgtype.UUID) ([]GetStadiumSummaryRow, error) {
	rows, err := q.db.Query(ctx, getStadiumSummary, filterOrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStadiumSummaryRow{}
	for rows.Next() {
		var i GetStadiumSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.State,
			&i.Capacity,
			&i.EventCount,
			&i.TotalSeats,
			&i.TicketsSold,
			&i.RevenueCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketFinancials = `-- name: GetTicketFinancials :one
SELECT
    COUNT(t.id) FILTER (WHERE o.status = 'PAID')::bigint                                                                           AS tickets_all,
    COUNT(t.id) FILTER (WHERE o.status = 'PAID' AND o.created_at >= NOW() - INTERVAL '30 days')::bigint                            AS tickets_30d,
    COALESCE(SUM(s.price_cents) FILTER (WHERE o.status = 'PAID'), 0)::bigint                                                       AS base_cents_all,
    COALESCE(SUM(s.price_cents) FILTER (WHERE o.status = 'PAID' AND o.created_at >= NOW() - INTERVAL '30 days'), 0)::bigint        AS base_cents_30d
FROM tickets t
JOIN orders o ON o.id = t.order_id
JOIN seats s ON s.id = t.seat_id
JOIN events e ON e.id = t.event_id
JOIN venues v ON v.id = e.venue_id
WHERE ($1::uuid IS NULL OR v.organization_id = $1)
`

type GetTicketFinancialsRow struct {
	TicketsAll   int64 `json:"tickets_all"`
	Tickets30d   int64 `json:"tickets_30d"`
	BaseCentsAll int64 `json:"base_cents_all"`
	BaseCents30d int64 `json:"base_cents_30d"`
}

func (q *Queries) GetTicketFinancials(ctx context.Context, filterOrganizationID pgtype.UUID) (GetTicketFinancialsRow, error) {
	row := q.db.QueryRow(ctx, getTicketFinancials, filterOrganizationID)
	var i GetTicketFinancialsRow
	err := row.Scan(
		&i.TicketsAll,
		&i.Tickets30d,
		&i.BaseCentsAll,
		&i.BaseCents30d,
	)
	return i, err
}

const getTicketStatusCounts = `-- name: GetTicketStatusCounts :many
SELECT
    t.status,
    COUNT(*)::bigint AS count
FROM tickets t
JOIN events e ON e.id = t.event_id
JOIN venues v ON v.id = e.venue_id
WHERE ($1::uuid IS NULL OR v.organization_id = $1)
GROUP BY t.status
`

type GetTicketStatusCountsRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetTicketStatusCounts(ctx context.Context, filterOrganizationID pgtype.UUID) ([]GetTicketStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, getTicketStatusCounts, filterOrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTicketStatusCountsRow{}
	for rows.Next() {
		var i GetTicketStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketsBySection = `-- name: GetTicketsBySection :many
SELECT
    s.section,
    COUNT(*)::bigint AS tickets_count
FROM tickets t
JOIN orders o ON o.id = t.order_id
JOIN seats s ON s.id = t.seat_id
JOIN events e ON e.id = t.event_id
JOIN venues v ON v.id = e.venue_id
WHERE o.status = 'PAID'
  AND ($1::uuid IS NULL OR v.organization_id = $1)
GROUP BY s.section
ORDER BY tickets_count DESC
LIMIT 10
`

type GetTicketsBySectionRow struct {
	Section      string `json:"section"`
	TicketsCount int64  `json:"tickets_count"`
}

func (q *Queries) GetTicketsBySection(ctx context.Context, filterOrganizationID pgtype.UUID) ([]GetTicketsBySectionRow, error) {
	rows, err := q.db.Query(ctx, getTicketsBySection, filterOrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTicketsBySectionRow{}
	for rows.Next() {
		var i GetTicketsBySectionRow
		if err := rows.Scan(&i.Section, &i.TicketsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketsBySport = `-- name: GetTicketsBySport :many
SELECT
    e.sport,
    COUNT(*)::bigint AS tickets_count
FROM tickets t
JOIN orders o ON o.id = t.order_id
JOIN events e ON e.id = t.event_id
JOIN venues v ON v.id = e.venue_id
WHERE o.status = 'PAID'
  AND ($1::uuid IS NULL OR v.organization_id = $1)
GROUP BY e.sport
ORDER BY tickets_count DESC
`

type GetTicketsBySportRow struct {
	Sport        string `json:"sport"`
	TicketsCount int64  `json:"tickets_count"`
}

func (q *Queries) GetTicketsBySport(ctx context.Context, filterOrganizationID pgtype.UUID) ([]GetTicketsBySportRow, error) {
	rows, err := q.db.Query(ctx, getTicketsBySport, filterOrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTicketsBySportRow{}
	for rows.Next() {
		var i GetTicketsBySportRow
		if err := rows.Scan(&i.Sport, &i.TicketsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopEventsByTickets = `-- name: GetTopEventsByTickets :many
SELECT
    e.id                                                                                      AS event_id,
    e.title,
    e.home_team,
    e.away_team,
    v.name                                                                                    AS venue_name,
    COUNT(CASE WHEN o.status = 'PAID' THEN t.id END)::bigint                                  AS tickets_sold,
    COALESCE(SUM(CASE WHEN o.status = 'PAID' THEN s.price_cents ELSE 0 END), 0)::bigint       AS revenue_cents
FROM events e
JOIN venues v ON v.id = e.venue_id
LEFT JOIN tickets t ON t.event_id = e.id
LEFT JOIN orders o ON o.id = t.order_id
LEFT JOIN seats s ON s.id = t.seat_id
WHERE e.deleted_at IS NULL
  AND ($1::uuid IS NULL OR v.organization_id = $1)
GROUP BY e.id, e.title, e.home_team, e.away_team, v.name
ORDER BY tickets_sold DESC, e.created_at DESC
LIMIT 5
`

type GetTopEventsByTicketsRow struct {
	EventID      uuid.UUID `json:"event_id"`
	Title        string    `json:"title"`
	HomeTeam     string    `json:"home_team"`
	AwayTeam     string    `json:"away_team"`
	VenueName    string    `json:"venue_name"`
	TicketsSold  int64     `json:"tickets_sold"`
	RevenueCents int64     `json:"revenue_cents"`
}

func (q *Queries) GetTopEventsByTickets(ctx context.Context, filterOrganizationID pgtype.UUID) ([]GetTopEventsByTicketsRow, error) {
	rows, err := q.db.Query(ctx, getTopEventsByTickets, filterOrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopEventsByTicketsRow{}
	for rows.Next() {
		var i GetTopEventsByTicketsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.VenueName,
			&i.TicketsSold,
			&i.RevenueCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
