// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, title, sport, league, venue_id, starts_at, status, service_fee_percent, home_team, away_team, image_url, vibe_chips)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, title, sport, league, venue_id, starts_at, status, service_fee_percent, home_team, away_team, image_url, vibe_chips, created_at, updated_at, deleted_at
`

type CreateEventParams struct {
	ID                uuid.UUID      `json:"id"`
	Title             string         `json:"title"`
	Sport             string         `json:"sport"`
	League            string         `json:"league"`
	VenueID           uuid.UUID      `json:"venue_id"`
	StartsAt          time.Time      `json:"starts_at"`
	Status            string         `json:"status"`
	ServiceFeePercent pgtype.Numeric `json:"service_fee_percent"`
	HomeTeam          string         `json:"home_team"`
	AwayTeam          string         `json:"away_team"`
	ImageUrl          string         `json:"image_url"`
	VibeChips         []string       `json:"vibe_chips"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.Title,
		arg.Sport,
		arg.League,
		arg.VenueID,
		arg.StartsAt,
		arg.Status,
		arg.ServiceFeePercent,
		arg.HomeTeam,
		arg.AwayTeam,
		arg.ImageUrl,
		arg.VibeChips,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Sport,
		&i.League,
		&i.VenueID,
		&i.StartsAt,
		&i.Status,
		&i.ServiceFeePercent,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.ImageUrl,
		&i.VibeChips,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    e.id, e.title, e.sport, e.league, e.venue_id, e.starts_at, e.status, e.service_fee_percent, e.home_team, e.away_team, e.image_url, e.vibe_chips, e.created_at, e.updated_at, e.deleted_at,
    v.id AS venue_id_2, v.name AS venue_name, v.city AS venue_city, v.state AS venue_state, v.capacity AS venue_capacity,
    COALESCE((SELECT MIN(s.price_cents) FROM seats s WHERE s.event_id = e.id AND s.status = 'AVAILABLE'), 0) AS min_price_cents,
    COALESCE((SELECT MAX(s.price_cents) FROM seats s WHERE s.event_id = e.id AND s.status = 'AVAILABLE'), 0) AS max_price_cents
FROM events e
JOIN venues v ON v.id = e.venue_id
WHERE e.id = $1 AND e.deleted_at IS NULL
`

type GetEventByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	Sport             string             `json:"sport"`
	League            string             `json:"league"`
	VenueID           uuid.UUID          `json:"venue_id"`
	StartsAt          time.Time          `json:"starts_at"`
	Status            string             `json:"status"`
	ServiceFeePercent pgtype.Numeric     `json:"service_fee_percent"`
	HomeTeam          string             `json:"home_team"`
	AwayTeam          string             `json:"away_team"`
	ImageUrl          string             `json:"image_url"`
	VibeChips         []string           `json:"vibe_chips"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	VenueID2          uuid.UUID          `json:"venue_id_2"`
	VenueName         string             `json:"venue_name"`
	VenueCity         string             `json:"venue_city"`
	VenueState        string             `json:"venue_state"`
	VenueCapacity     int32              `json:"venue_capacity"`
	MinPriceCents     interface{}        `json:"min_price_cents"`
	MaxPriceCents     interface{}        `json:"max_price_cents"`
}

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Sport,
		&i.League,
		&i.VenueID,
		&i.StartsAt,
		&i.Status,
		&i.ServiceFeePercent,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.ImageUrl,
		&i.VibeChips,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.VenueID2,
		&i.VenueName,
		&i.VenueCity,
		&i.VenueState,
		&i.VenueCapacity,
		&i.MinPriceCents,
		&i.MaxPriceCents,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT
    e.id, e.title, e.sport, e.league, e.venue_id, e.starts_at, e.status, e.service_fee_percent, e.home_team, e.away_team, e.image_url, e.vibe_chips, e.created_at, e.updated_at, e.deleted_at,
    v.id AS venue_id_2, v.name AS venue_name, v.city AS venue_city, v.state AS venue_state, v.capacity AS venue_capacity,
    COALESCE((SELECT MIN(s.price_cents) FROM seats s WHERE s.event_id = e.id AND s.status = 'AVAILABLE'), 0) AS min_price_cents,
    COALESCE((SELECT MAX(s.price_cents) FROM seats s WHERE s.event_id = e.id AND s.status = 'AVAILABLE'), 0) AS max_price_cents
FROM events e
JOIN venues v ON v.id = e.venue_id
WHERE e.deleted_at IS NULL
    AND ($1::VARCHAR IS NULL OR e.sport = $1)
    AND ($2::VARCHAR IS NULL OR e.league = $2)
    AND ($3::VARCHAR IS NULL OR v.city = $3)
    AND ($4::DATE IS NULL OR DATE(e.starts_at) = $4::DATE)
ORDER BY e.starts_at ASC
LIMIT $6 OFFSET $5
`

type ListEventsParams struct {
	Sport       pgtype.Text `json:"sport"`
	League      pgtype.Text `json:"league"`
	City        pgtype.Text `json:"city"`
	Date        pgtype.Date `json:"date"`
	QueryOffset int32       `json:"query_offset"`
	QueryLimit  int32       `json:"query_limit"`
}

type ListEventsRow struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	Sport             string             `json:"sport"`
	League            string             `json:"league"`
	VenueID           uuid.UUID          `json:"venue_id"`
	StartsAt          time.Time          `json:"starts_at"`
	Status            string             `json:"status"`
	ServiceFeePercent pgtype.Numeric     `json:"service_fee_percent"`
	HomeTeam          string             `json:"home_team"`
	AwayTeam          string             `json:"away_team"`
	ImageUrl          string             `json:"image_url"`
	VibeChips         []string           `json:"vibe_chips"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	VenueID2          uuid.UUID          `json:"venue_id_2"`
	VenueName         string             `json:"venue_name"`
	VenueCity         string             `json:"venue_city"`
	VenueState        string             `json:"venue_state"`
	VenueCapacity     int32              `json:"venue_capacity"`
	MinPriceCents     interface{}        `json:"min_price_cents"`
	MaxPriceCents     interface{}        `json:"max_price_cents"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.Sport,
		arg.League,
		arg.City,
		arg.Date,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Sport,
			&i.League,
			&i.VenueID,
			&i.StartsAt,
			&i.Status,
			&i.ServiceFeePercent,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.ImageUrl,
			&i.VibeChips,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.VenueID2,
			&i.VenueName,
			&i.VenueCity,
			&i.VenueState,
			&i.VenueCapacity,
			&i.MinPriceCents,
			&i.MaxPriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events
SET title = $2, sport = $3, league = $4, venue_id = $5, starts_at = $6, status = $7, service_fee_percent = $8, home_team = $9, away_team = $10, image_url = $11, vibe_chips = $12
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateEventParams struct {
	ID                uuid.UUID      `json:"id"`
	Title             string         `json:"title"`
	Sport             string         `json:"sport"`
	League            string         `json:"league"`
	VenueID           uuid.UUID      `json:"venue_id"`
	StartsAt          time.Time      `json:"starts_at"`
	Status            string         `json:"status"`
	ServiceFeePercent pgtype.Numeric `json:"service_fee_percent"`
	HomeTeam          string         `json:"home_team"`
	AwayTeam          string         `json:"away_team"`
	ImageUrl          string         `json:"image_url"`
	VibeChips         []string       `json:"vibe_chips"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.Exec(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Sport,
		arg.League,
		arg.VenueID,
		arg.StartsAt,
		arg.Status,
		arg.ServiceFeePercent,
		arg.HomeTeam,
		arg.AwayTeam,
		arg.ImageUrl,
		arg.VibeChips,
	)
	return err
}
