// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	Sport             string             `json:"sport"`
	League            string             `json:"league"`
	VenueID           uuid.UUID          `json:"venue_id"`
	StartsAt          time.Time          `json:"starts_at"`
	Status            string             `json:"status"`
	ServiceFeePercent pgtype.Numeric     `json:"service_fee_percent"`
	HomeTeam          string             `json:"home_team"`
	AwayTeam          string             `json:"away_team"`
	ImageUrl          string             `json:"image_url"`
	VibeChips         []string           `json:"vibe_chips"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Order struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	TotalCents      int64     `json:"total_cents"`
	StripePaymentID string    `json:"stripe_payment_id"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type OrderReservation struct {
	OrderID       uuid.UUID `json:"order_id"`
	ReservationID uuid.UUID `json:"reservation_id"`
}

type Reservation struct {
	ID        uuid.UUID `json:"id"`
	SeatID    uuid.UUID `json:"seat_id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Seat struct {
	ID         uuid.UUID `json:"id"`
	EventID    uuid.UUID `json:"event_id"`
	Section    string    `json:"section"`
	Row        string    `json:"row"`
	Number     string    `json:"number"`
	PriceCents int64     `json:"price_cents"`
	Status     string    `json:"status"`
	Col        int32     `json:"col"`
	RowIndex   int32     `json:"row_index"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Ticket struct {
	ID          uuid.UUID `json:"id"`
	OrderID     uuid.UUID `json:"order_id"`
	EventID     uuid.UUID `json:"event_id"`
	SeatID      uuid.UUID `json:"seat_id"`
	QrCode      string    `json:"qr_code"`
	Status      string    `json:"status"`
	PurchasedAt time.Time `json:"purchased_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CpfHash      string             `json:"cpf_hash"`
	Phone        string             `json:"phone"`
	Role         string             `json:"role"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Venue struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	City      string             `json:"city"`
	State     string             `json:"state"`
	Capacity  int32              `json:"capacity"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
