// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, total_cents, stripe_payment_id, status,
  buyer_name, buyer_email, buyer_cpf, buyer_phone,
  buyer_cep, buyer_street, buyer_neighborhood, buyer_city, buyer_state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, user_id, total_cents, stripe_payment_id, status, created_at, updated_at, buyer_name, buyer_email, buyer_cpf, buyer_phone, buyer_cep, buyer_street, buyer_neighborhood, buyer_city, buyer_state
`

type CreateOrderParams struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	TotalCents        int64     `json:"total_cents"`
	StripePaymentID   string    `json:"stripe_payment_id"`
	Status            string    `json:"status"`
	BuyerName         string    `json:"buyer_name"`
	BuyerEmail        string    `json:"buyer_email"`
	BuyerCpf          string    `json:"buyer_cpf"`
	BuyerPhone        string    `json:"buyer_phone"`
	BuyerCep          string    `json:"buyer_cep"`
	BuyerStreet       string    `json:"buyer_street"`
	BuyerNeighborhood string    `json:"buyer_neighborhood"`
	BuyerCity         string    `json:"buyer_city"`
	BuyerState        string    `json:"buyer_state"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.TotalCents,
		arg.StripePaymentID,
		arg.Status,
		arg.BuyerName,
		arg.BuyerEmail,
		arg.BuyerCpf,
		arg.BuyerPhone,
		arg.BuyerCep,
		arg.BuyerStreet,
		arg.BuyerNeighborhood,
		arg.BuyerCity,
		arg.BuyerState,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalCents,
		&i.StripePaymentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerCpf,
		&i.BuyerPhone,
		&i.BuyerCep,
		&i.BuyerStreet,
		&i.BuyerNeighborhood,
		&i.BuyerCity,
		&i.BuyerState,
	)
	return i, err
}

const createOrderReservation = `-- name: CreateOrderReservation :exec
INSERT INTO order_reservations (order_id, reservation_id)
VALUES ($1, $2)
`

type CreateOrderReservationParams struct {
	OrderID       uuid.UUID `json:"order_id"`
	ReservationID uuid.UUID `json:"reservation_id"`
}

func (q *Queries) CreateOrderReservation(ctx context.Context, arg CreateOrderReservationParams) error {
	_, err := q.db.Exec(ctx, createOrderReservation, arg.OrderID, arg.ReservationID)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, total_cents, stripe_payment_id, status, created_at, updated_at, buyer_name, buyer_email, buyer_cpf, buyer_phone, buyer_cep, buyer_street, buyer_neighborhood, buyer_city, buyer_state FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalCents,
		&i.StripePaymentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerCpf,
		&i.BuyerPhone,
		&i.BuyerCep,
		&i.BuyerStreet,
		&i.BuyerNeighborhood,
		&i.BuyerCity,
		&i.BuyerState,
	)
	return i, err
}

const listOrderReservationIDs = `-- name: ListOrderReservationIDs :many
SELECT reservation_id FROM order_reservations WHERE order_id = $1
`

func (q *Queries) ListOrderReservationIDs(ctx context.Context, orderID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOrderReservationIDs, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var reservation_id uuid.UUID
		if err := rows.Scan(&reservation_id); err != nil {
			return nil, err
		}
		items = append(items, reservation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, user_id, total_cents, stripe_payment_id, status, created_at, updated_at, buyer_name, buyer_email, buyer_cpf, buyer_phone, buyer_cep, buyer_street, buyer_neighborhood, buyer_city, buyer_state FROM orders WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalCents,
			&i.StripePaymentID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BuyerName,
			&i.BuyerEmail,
			&i.BuyerCpf,
			&i.BuyerPhone,
			&i.BuyerCep,
			&i.BuyerStreet,
			&i.BuyerNeighborhood,
			&i.BuyerCity,
			&i.BuyerState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $2 WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}

const updateOrderStripePaymentID = `-- name: UpdateOrderStripePaymentID :exec
UPDATE orders SET stripe_payment_id = $2 WHERE id = $1
`

type UpdateOrderStripePaymentIDParams struct {
	ID              uuid.UUID `json:"id"`
	StripePaymentID string    `json:"stripe_payment_id"`
}

func (q *Queries) UpdateOrderStripePaymentID(ctx context.Context, arg UpdateOrderStripePaymentIDParams) error {
	_, err := q.db.Exec(ctx, updateOrderStripePaymentID, arg.ID, arg.StripePaymentID)
	return err
}
