// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*) FROM organizations WHERE deleted_at IS NULL
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, slug, subscription_status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, created_at, updated_at, deleted_at
`

type CreateOrganizationParams struct {
	ID                 uuid.UUID `json:"id"`
	Name               string    `json:"name"`
	Slug               string    `json:"slug"`
	SubscriptionStatus string    `json:"subscription_status"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.SubscriptionStatus,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, created_at, updated_at, deleted_at FROM organizations WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, created_at, updated_at, deleted_at FROM organizations WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, created_at, updated_at, deleted_at FROM organizations
WHERE deleted_at IS NULL
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.SubscriptionStatus,
			&i.CurrentPeriodEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET name = $2, slug = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateOrganizationParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateOrganization, arg.ID, arg.Name, arg.Slug)
	return err
}

const updateOrganizationSubscription = `-- name: UpdateOrganizationSubscription :exec
UPDATE organizations
SET
    stripe_customer_id     = $2,
    stripe_subscription_id = $3,
    subscription_status    = $4,
    current_period_end     = $5,
    updated_at             = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateOrganizationSubscriptionParams struct {
	ID                   uuid.UUID          `json:"id"`
	StripeCustomerID     string             `json:"stripe_customer_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	SubscriptionStatus   string             `json:"subscription_status"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpdateOrganizationSubscription(ctx context.Context, arg UpdateOrganizationSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationSubscription,
		arg.ID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.SubscriptionStatus,
		arg.CurrentPeriodEnd,
	)
	return err
}
