// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resale_listing_holds.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const expireStaleResaleListingHolds = `-- name: ExpireStaleResaleListingHolds :exec
UPDATE resale_listing_holds
SET status = 'EXPIRED', updated_at = NOW()
WHERE status = 'ACTIVE' AND expires_at <= NOW()
`

func (q *Queries) ExpireStaleResaleListingHolds(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireStaleResaleListingHolds)
	return err
}

const getActiveResaleListingHoldByListingID = `-- name: GetActiveResaleListingHoldByListingID :one
SELECT id, resale_listing_id, user_id, expires_at, status, created_at, updated_at FROM resale_listing_holds
WHERE resale_listing_id = $1 AND status = 'ACTIVE' AND expires_at > NOW()
`

func (q *Queries) GetActiveResaleListingHoldByListingID(ctx context.Context, resaleListingID uuid.UUID) (ResaleListingHold, error) {
	row := q.db.QueryRow(ctx, getActiveResaleListingHoldByListingID, resaleListingID)
	var i ResaleListingHold
	err := row.Scan(
		&i.ID,
		&i.ResaleListingID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResaleListingHoldByID = `-- name: GetResaleListingHoldByID :one
SELECT id, resale_listing_id, user_id, expires_at, status, created_at, updated_at FROM resale_listing_holds WHERE id = $1
`

func (q *Queries) GetResaleListingHoldByID(ctx context.Context, id uuid.UUID) (ResaleListingHold, error) {
	row := q.db.QueryRow(ctx, getResaleListingHoldByID, id)
	var i ResaleListingHold
	err := row.Scan(
		&i.ID,
		&i.ResaleListingID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertResaleListingHold = `-- name: InsertResaleListingHold :one
INSERT INTO resale_listing_holds (id, resale_listing_id, user_id, expires_at, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, resale_listing_id, user_id, expires_at, status, created_at, updated_at
`

type InsertResaleListingHoldParams struct {
	ID              uuid.UUID `json:"id"`
	ResaleListingID uuid.UUID `json:"resale_listing_id"`
	UserID          uuid.UUID `json:"user_id"`
	ExpiresAt       time.Time `json:"expires_at"`
	Status          string    `json:"status"`
}

func (q *Queries) InsertResaleListingHold(ctx context.Context, arg InsertResaleListingHoldParams) (ResaleListingHold, error) {
	row := q.db.QueryRow(ctx, insertResaleListingHold,
		arg.ID,
		arg.ResaleListingID,
		arg.UserID,
		arg.ExpiresAt,
		arg.Status,
	)
	var i ResaleListingHold
	err := row.Scan(
		&i.ID,
		&i.ResaleListingID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markResaleListingHoldConverted = `-- name: MarkResaleListingHoldConverted :one
UPDATE resale_listing_holds
SET status = 'CONVERTED', updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND status = 'ACTIVE' AND expires_at > NOW()
RETURNING id, resale_listing_id, user_id, expires_at, status, created_at, updated_at
`

type MarkResaleListingHoldConvertedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkResaleListingHoldConverted(ctx context.Context, arg MarkResaleListingHoldConvertedParams) (ResaleListingHold, error) {
	row := q.db.QueryRow(ctx, markResaleListingHoldConverted, arg.ID, arg.UserID)
	var i ResaleListingHold
	err := row.Scan(
		&i.ID,
		&i.ResaleListingID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markResaleListingHoldExpiredByUser = `-- name: MarkResaleListingHoldExpiredByUser :exec
UPDATE resale_listing_holds
SET status = 'EXPIRED', updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND status = 'ACTIVE'
`

type MarkResaleListingHoldExpiredByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkResaleListingHoldExpiredByUser(ctx context.Context, arg MarkResaleListingHoldExpiredByUserParams) error {
	_, err := q.db.Exec(ctx, markResaleListingHoldExpiredByUser, arg.ID, arg.UserID)
	return err
}

const revertResaleListingHoldToActive = `-- name: RevertResaleListingHoldToActive :exec
UPDATE resale_listing_holds
SET status = 'ACTIVE', updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND status = 'CONVERTED'
`

type RevertResaleListingHoldToActiveParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevertResaleListingHoldToActive(ctx context.Context, arg RevertResaleListingHoldToActiveParams) error {
	_, err := q.db.Exec(ctx, revertResaleListingHoldToActive, arg.ID, arg.UserID)
	return err
}
