// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resale_listings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelTicketResaleListing = `-- name: CancelTicketResaleListing :exec
UPDATE ticket_resale_listings
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND seller_user_id = $2 AND status = 'active'
`

type CancelTicketResaleListingParams struct {
	ID           uuid.UUID `json:"id"`
	SellerUserID uuid.UUID `json:"seller_user_id"`
}

func (q *Queries) CancelTicketResaleListing(ctx context.Context, arg CancelTicketResaleListingParams) error {
	_, err := q.db.Exec(ctx, cancelTicketResaleListing, arg.ID, arg.SellerUserID)
	return err
}

const getActiveTicketResaleListingByTicketID = `-- name: GetActiveTicketResaleListingByTicketID :one
SELECT id, ticket_id, seller_user_id, price_cents, status, created_at, updated_at FROM ticket_resale_listings
WHERE ticket_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveTicketResaleListingByTicketID(ctx context.Context, ticketID uuid.UUID) (TicketResaleListing, error) {
	row := q.db.QueryRow(ctx, getActiveTicketResaleListingByTicketID, ticketID)
	var i TicketResaleListing
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.SellerUserID,
		&i.PriceCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketResaleListingByID = `-- name: GetTicketResaleListingByID :one
SELECT id, ticket_id, seller_user_id, price_cents, status, created_at, updated_at FROM ticket_resale_listings WHERE id = $1
`

func (q *Queries) GetTicketResaleListingByID(ctx context.Context, id uuid.UUID) (TicketResaleListing, error) {
	row := q.db.QueryRow(ctx, getTicketResaleListingByID, id)
	var i TicketResaleListing
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.SellerUserID,
		&i.PriceCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPendingResaleOrderForListing = `-- name: HasPendingResaleOrderForListing :one
SELECT EXISTS (
    SELECT 1 FROM orders o
    WHERE o.resale_listing_id = $1 AND o.status = 'PENDING' AND o.kind = 'resale'
) AS has_pending
`

func (q *Queries) HasPendingResaleOrderForListing(ctx context.Context, resaleListingID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingResaleOrderForListing, resaleListingID)
	var has_pending bool
	err := row.Scan(&has_pending)
	return has_pending, err
}

const insertTicketResaleListing = `-- name: InsertTicketResaleListing :one
INSERT INTO ticket_resale_listings (id, ticket_id, seller_user_id, price_cents, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticket_id, seller_user_id, price_cents, status, created_at, updated_at
`

type InsertTicketResaleListingParams struct {
	ID           uuid.UUID `json:"id"`
	TicketID     uuid.UUID `json:"ticket_id"`
	SellerUserID uuid.UUID `json:"seller_user_id"`
	PriceCents   int64     `json:"price_cents"`
	Status       string    `json:"status"`
}

func (q *Queries) InsertTicketResaleListing(ctx context.Context, arg InsertTicketResaleListingParams) (TicketResaleListing, error) {
	row := q.db.QueryRow(ctx, insertTicketResaleListing,
		arg.ID,
		arg.TicketID,
		arg.SellerUserID,
		arg.PriceCents,
		arg.Status,
	)
	var i TicketResaleListing
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.SellerUserID,
		&i.PriceCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveResaleListingsByEventID = `-- name: ListActiveResaleListingsByEventID :many
SELECT
    l.id,
    l.ticket_id,
    l.seller_user_id,
    l.price_cents,
    l.status,
    l.created_at,
    l.updated_at,
    t.event_id,
    s.section AS seat_section,
    s.row AS seat_row,
    s.number AS seat_number
FROM ticket_resale_listings l
JOIN tickets t ON t.id = l.ticket_id
JOIN seats s ON s.id = t.seat_id
WHERE t.event_id = $1 AND l.status = 'active'
ORDER BY l.price_cents ASC, l.created_at ASC
`

type ListActiveResaleListingsByEventIDRow struct {
	ID           uuid.UUID `json:"id"`
	TicketID     uuid.UUID `json:"ticket_id"`
	SellerUserID uuid.UUID `json:"seller_user_id"`
	PriceCents   int64     `json:"price_cents"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	EventID      uuid.UUID `json:"event_id"`
	SeatSection  string    `json:"seat_section"`
	SeatRow      string    `json:"seat_row"`
	SeatNumber   string    `json:"seat_number"`
}

func (q *Queries) ListActiveResaleListingsByEventID(ctx context.Context, eventID uuid.UUID) ([]ListActiveResaleListingsByEventIDRow, error) {
	rows, err := q.db.Query(ctx, listActiveResaleListingsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveResaleListingsByEventIDRow{}
	for rows.Next() {
		var i ListActiveResaleListingsByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.SellerUserID,
			&i.PriceCents,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventID,
			&i.SeatSection,
			&i.SeatRow,
			&i.SeatNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketResaleListingsBySellerUserID = `-- name: ListTicketResaleListingsBySellerUserID :many
SELECT id, ticket_id, seller_user_id, price_cents, status, created_at, updated_at FROM ticket_resale_listings
WHERE seller_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTicketResaleListingsBySellerUserID(ctx context.Context, sellerUserID uuid.UUID) ([]TicketResaleListing, error) {
	rows, err := q.db.Query(ctx, listTicketResaleListingsBySellerUserID, sellerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketResaleListing{}
	for rows.Next() {
		var i TicketResaleListing
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.SellerUserID,
			&i.PriceCents,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTicketResaleListingSold = `-- name: MarkTicketResaleListingSold :exec
UPDATE ticket_resale_listings
SET status = 'sold', updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) MarkTicketResaleListingSold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTicketResaleListingSold, id)
	return err
}
