// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (id, seat_id, user_id, expires_at, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, seat_id, user_id, expires_at, status, created_at, updated_at
`

type CreateReservationParams struct {
	ID        uuid.UUID `json:"id"`
	SeatID    uuid.UUID `json:"seat_id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Status    string    `json:"status"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ID,
		arg.SeatID,
		arg.UserID,
		arg.ExpiresAt,
		arg.Status,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.SeatID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveReservationBySeatID = `-- name: GetActiveReservationBySeatID :one
SELECT id, seat_id, user_id, expires_at, status, created_at, updated_at FROM reservations
WHERE seat_id = $1 AND status = 'ACTIVE' AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetActiveReservationBySeatID(ctx context.Context, seatID uuid.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getActiveReservationBySeatID, seatID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.SeatID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveStatusReservationBySeatID = `-- name: GetActiveStatusReservationBySeatID :one
SELECT id, seat_id, user_id, expires_at, status, created_at, updated_at FROM reservations
WHERE seat_id = $1 AND status = 'ACTIVE'
LIMIT 1
`

// Used when Redis lock TTL expires: DB expires_at may already be <= NOW(), so we must not filter on expires_at.
func (q *Queries) GetActiveStatusReservationBySeatID(ctx context.Context, seatID uuid.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getActiveStatusReservationBySeatID, seatID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.SeatID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, seat_id, user_id, expires_at, status, created_at, updated_at FROM reservations WHERE id = $1
`

func (q *Queries) GetReservationByID(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.SeatID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredActiveReservations = `-- name: ListExpiredActiveReservations :many
SELECT r.id AS reservation_id, r.seat_id, s.event_id
FROM reservations r
INNER JOIN seats s ON s.id = r.seat_id
WHERE r.status = 'ACTIVE' AND r.expires_at < NOW()
`

type ListExpiredActiveReservationsRow struct {
	ReservationID uuid.UUID `json:"reservation_id"`
	SeatID        uuid.UUID `json:"seat_id"`
	EventID       uuid.UUID `json:"event_id"`
}

func (q *Queries) ListExpiredActiveReservations(ctx context.Context) ([]ListExpiredActiveReservationsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredActiveReservationsRow{}
	for rows.Next() {
		var i ListExpiredActiveReservationsRow
		if err := rows.Scan(&i.ReservationID, &i.SeatID, &i.EventID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUserID = `-- name: ListReservationsByUserID :many
SELECT id, seat_id, user_id, expires_at, status, created_at, updated_at FROM reservations WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReservationsByUserID(ctx context.Context, userID uuid.UUID) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.SeatID,
			&i.UserID,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :exec
UPDATE reservations SET status = $2 WHERE id = $1
`

type UpdateReservationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationStatus, arg.ID, arg.Status)
	return err
}
