// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seats.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSeat = `-- name: CreateSeat :one
INSERT INTO seats (id, event_id, section, row, number, price_cents, status, col, row_index)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, event_id, section, row, number, price_cents, status, col, row_index, created_at, updated_at
`

type CreateSeatParams struct {
	ID         uuid.UUID `json:"id"`
	EventID    uuid.UUID `json:"event_id"`
	Section    string    `json:"section"`
	Row        string    `json:"row"`
	Number     string    `json:"number"`
	PriceCents int64     `json:"price_cents"`
	Status     string    `json:"status"`
	Col        int32     `json:"col"`
	RowIndex   int32     `json:"row_index"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, createSeat,
		arg.ID,
		arg.EventID,
		arg.Section,
		arg.Row,
		arg.Number,
		arg.PriceCents,
		arg.Status,
		arg.Col,
		arg.RowIndex,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Section,
		&i.Row,
		&i.Number,
		&i.PriceCents,
		&i.Status,
		&i.Col,
		&i.RowIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeatByID = `-- name: GetSeatByID :one
SELECT id, event_id, section, row, number, price_cents, status, col, row_index, created_at, updated_at FROM seats WHERE id = $1
`

func (q *Queries) GetSeatByID(ctx context.Context, id uuid.UUID) (Seat, error) {
	row := q.db.QueryRow(ctx, getSeatByID, id)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Section,
		&i.Row,
		&i.Number,
		&i.PriceCents,
		&i.Status,
		&i.Col,
		&i.RowIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSeatsByEventID = `-- name: ListSeatsByEventID :many
SELECT id, event_id, section, row, number, price_cents, status, col, row_index, created_at, updated_at FROM seats WHERE event_id = $1 ORDER BY section, row_index, col
`

func (q *Queries) ListSeatsByEventID(ctx context.Context, eventID uuid.UUID) ([]Seat, error) {
	rows, err := q.db.Query(ctx, listSeatsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Section,
			&i.Row,
			&i.Number,
			&i.PriceCents,
			&i.Status,
			&i.Col,
			&i.RowIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeatStatus = `-- name: UpdateSeatStatus :exec
UPDATE seats SET status = $2 WHERE id = $1
`

type UpdateSeatStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSeatStatus(ctx context.Context, arg UpdateSeatStatusParams) error {
	_, err := q.db.Exec(ctx, updateSeatStatus, arg.ID, arg.Status)
	return err
}
