// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stripe_webhook_inbox.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertStripeProcessedWebhookEvent = `-- name: InsertStripeProcessedWebhookEvent :exec
INSERT INTO stripe_processed_webhook_events (stripe_event_id, inbox_id)
VALUES ($1, $2)
`

type InsertStripeProcessedWebhookEventParams struct {
	StripeEventID string    `json:"stripe_event_id"`
	InboxID       uuid.UUID `json:"inbox_id"`
}

func (q *Queries) InsertStripeProcessedWebhookEvent(ctx context.Context, arg InsertStripeProcessedWebhookEventParams) error {
	_, err := q.db.Exec(ctx, insertStripeProcessedWebhookEvent, arg.StripeEventID, arg.InboxID)
	return err
}

const insertStripeWebhookInbox = `-- name: InsertStripeWebhookInbox :one
INSERT INTO stripe_webhook_inbox (raw_body, stripe_signature, status)
VALUES ($1, $2, 'pending')
RETURNING id, created_at
`

type InsertStripeWebhookInboxParams struct {
	RawBody         []byte `json:"raw_body"`
	StripeSignature string `json:"stripe_signature"`
}

type InsertStripeWebhookInboxRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertStripeWebhookInbox(ctx context.Context, arg InsertStripeWebhookInboxParams) (InsertStripeWebhookInboxRow, error) {
	row := q.db.QueryRow(ctx, insertStripeWebhookInbox, arg.RawBody, arg.StripeSignature)
	var i InsertStripeWebhookInboxRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const updateStripeWebhookInboxDuplicate = `-- name: UpdateStripeWebhookInboxDuplicate :exec
UPDATE stripe_webhook_inbox
SET status = 'duplicate_event',
    stripe_event_id = $2,
    event_type = $3,
    processed_at = now()
WHERE id = $1
`

type UpdateStripeWebhookInboxDuplicateParams struct {
	ID            uuid.UUID   `json:"id"`
	StripeEventID pgtype.Text `json:"stripe_event_id"`
	EventType     pgtype.Text `json:"event_type"`
}

func (q *Queries) UpdateStripeWebhookInboxDuplicate(ctx context.Context, arg UpdateStripeWebhookInboxDuplicateParams) error {
	_, err := q.db.Exec(ctx, updateStripeWebhookInboxDuplicate, arg.ID, arg.StripeEventID, arg.EventType)
	return err
}

const updateStripeWebhookInboxFailed = `-- name: UpdateStripeWebhookInboxFailed :exec
UPDATE stripe_webhook_inbox
SET status = 'failed',
    stripe_event_id = COALESCE($2, stripe_event_id),
    event_type = COALESCE($3, event_type),
    error_message = $4,
    processed_at = now()
WHERE id = $1
`

type UpdateStripeWebhookInboxFailedParams struct {
	ID            uuid.UUID   `json:"id"`
	StripeEventID pgtype.Text `json:"stripe_event_id"`
	EventType     pgtype.Text `json:"event_type"`
	ErrorMessage  pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateStripeWebhookInboxFailed(ctx context.Context, arg UpdateStripeWebhookInboxFailedParams) error {
	_, err := q.db.Exec(ctx, updateStripeWebhookInboxFailed,
		arg.ID,
		arg.StripeEventID,
		arg.EventType,
		arg.ErrorMessage,
	)
	return err
}

const updateStripeWebhookInboxInvalid = `-- name: UpdateStripeWebhookInboxInvalid :exec
UPDATE stripe_webhook_inbox
SET status = 'invalid_signature',
    error_message = $2,
    processed_at = now()
WHERE id = $1
`

type UpdateStripeWebhookInboxInvalidParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateStripeWebhookInboxInvalid(ctx context.Context, arg UpdateStripeWebhookInboxInvalidParams) error {
	_, err := q.db.Exec(ctx, updateStripeWebhookInboxInvalid, arg.ID, arg.ErrorMessage)
	return err
}

const updateStripeWebhookInboxProcessed = `-- name: UpdateStripeWebhookInboxProcessed :exec
UPDATE stripe_webhook_inbox
SET status = 'processed',
    stripe_event_id = $2,
    event_type = $3,
    processed_at = now()
WHERE id = $1
`

type UpdateStripeWebhookInboxProcessedParams struct {
	ID            uuid.UUID   `json:"id"`
	StripeEventID pgtype.Text `json:"stripe_event_id"`
	EventType     pgtype.Text `json:"event_type"`
}

func (q *Queries) UpdateStripeWebhookInboxProcessed(ctx context.Context, arg UpdateStripeWebhookInboxProcessedParams) error {
	_, err := q.db.Exec(ctx, updateStripeWebhookInboxProcessed, arg.ID, arg.StripeEventID, arg.EventType)
	return err
}
