// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (id, order_id, event_id, seat_id, qr_code, status, purchased_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, order_id, event_id, seat_id, qr_code, status, purchased_at, created_at, updated_at
`

type CreateTicketParams struct {
	ID          uuid.UUID `json:"id"`
	OrderID     uuid.UUID `json:"order_id"`
	EventID     uuid.UUID `json:"event_id"`
	SeatID      uuid.UUID `json:"seat_id"`
	QrCode      string    `json:"qr_code"`
	Status      string    `json:"status"`
	PurchasedAt time.Time `json:"purchased_at"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ID,
		arg.OrderID,
		arg.EventID,
		arg.SeatID,
		arg.QrCode,
		arg.Status,
		arg.PurchasedAt,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.EventID,
		&i.SeatID,
		&i.QrCode,
		&i.Status,
		&i.PurchasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, order_id, event_id, seat_id, qr_code, status, purchased_at, created_at, updated_at FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.EventID,
		&i.SeatID,
		&i.QrCode,
		&i.Status,
		&i.PurchasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketsByOrderID = `-- name: ListTicketsByOrderID :many
SELECT id, order_id, event_id, seat_id, qr_code, status, purchased_at, created_at, updated_at FROM tickets WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListTicketsByOrderID(ctx context.Context, orderID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.EventID,
			&i.SeatID,
			&i.QrCode,
			&i.Status,
			&i.PurchasedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByUserID = `-- name: ListTicketsByUserID :many
SELECT t.id, t.order_id, t.event_id, t.seat_id, t.qr_code, t.status, t.purchased_at, t.created_at, t.updated_at FROM tickets t
JOIN orders o ON o.id = t.order_id
WHERE o.user_id = $1
ORDER BY t.purchased_at DESC
`

func (q *Queries) ListTicketsByUserID(ctx context.Context, userID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.EventID,
			&i.SeatID,
			&i.QrCode,
			&i.Status,
			&i.PurchasedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
