// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password_hash, cpf_hash, phone, role, organization_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, email, password_hash, cpf_hash, phone, role, created_at, updated_at, deleted_at, organization_id, stripe_connect_account_id, stripe_connect_charges_enabled
`

type CreateUserParams struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	Email          string      `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	CpfHash        string      `json:"cpf_hash"`
	Phone          string      `json:"phone"`
	Role           string      `json:"role"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.CpfHash,
		arg.Phone,
		arg.Role,
		arg.OrganizationID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CpfHash,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrganizationID,
		&i.StripeConnectAccountID,
		&i.StripeConnectChargesEnabled,
	)
	return i, err
}

const existsByCPFHash = `-- name: ExistsByCPFHash :one
SELECT EXISTS(SELECT 1 FROM users WHERE cpf_hash = $1 AND deleted_at IS NULL)
`

func (q *Queries) ExistsByCPFHash(ctx context.Context, cpfHash string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByCPFHash, cpfHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, cpf_hash, phone, role, created_at, updated_at, deleted_at, organization_id, stripe_connect_account_id, stripe_connect_charges_enabled FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CpfHash,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrganizationID,
		&i.StripeConnectAccountID,
		&i.StripeConnectChargesEnabled,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, cpf_hash, phone, role, created_at, updated_at, deleted_at, organization_id, stripe_connect_account_id, stripe_connect_charges_enabled FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CpfHash,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrganizationID,
		&i.StripeConnectAccountID,
		&i.StripeConnectChargesEnabled,
	)
	return i, err
}

const setUserOrganizationAndRole = `-- name: SetUserOrganizationAndRole :exec
UPDATE users
SET organization_id = $2, role = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type SetUserOrganizationAndRoleParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Role           string      `json:"role"`
}

func (q *Queries) SetUserOrganizationAndRole(ctx context.Context, arg SetUserOrganizationAndRoleParams) error {
	_, err := q.db.Exec(ctx, setUserOrganizationAndRole, arg.ID, arg.OrganizationID, arg.Role)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = $2, email = $3, phone = $4
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
	Phone string    `json:"phone"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStripeConnect = `-- name: UpdateUserStripeConnect :exec
UPDATE users
SET stripe_connect_account_id = $2,
    stripe_connect_charges_enabled = $3,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserStripeConnectParams struct {
	ID                          uuid.UUID `json:"id"`
	StripeConnectAccountID      string    `json:"stripe_connect_account_id"`
	StripeConnectChargesEnabled bool      `json:"stripe_connect_charges_enabled"`
}

func (q *Queries) UpdateUserStripeConnect(ctx context.Context, arg UpdateUserStripeConnectParams) error {
	_, err := q.db.Exec(ctx, updateUserStripeConnect, arg.ID, arg.StripeConnectAccountID, arg.StripeConnectChargesEnabled)
	return err
}
