// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (id, name, city, state, capacity, organization_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, city, state, capacity, created_at, updated_at, deleted_at, organization_id
`

type CreateVenueParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	City           string    `json:"city"`
	State          string    `json:"state"`
	Capacity       int32     `json:"capacity"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.ID,
		arg.Name,
		arg.City,
		arg.State,
		arg.Capacity,
		arg.OrganizationID,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.State,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, name, city, state, capacity, created_at, updated_at, deleted_at, organization_id FROM venues WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVenueByID(ctx context.Context, id uuid.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.State,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrganizationID,
	)
	return i, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, name, city, state, capacity, created_at, updated_at, deleted_at, organization_id FROM venues WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.State,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
